; Inno Setup Script for VoiceToText Pro (Phoenix Voice Studio)
; Generated by Project Roadmap Manager

#define MyAppName "VoiceToText Pro"
#define MyAppVersion "2.0.0"
#define MyAppPublisher "Phoenix Voice Studio Team"
#define MyAppURL "https://github.com/user/VoiceToTextPro"
#define MyAppExeName "VoiceToTextPro.exe"

[Setup]
AppId={{9E18A4F3-68D7-4B22-8611-C7F1388E919B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename=VoiceToTextPro_Setup_v2.0.0
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\{#MyAppExeName}
SetupIconFile=d:\VoiceToText\new_version\VoiceToTextPro\AppIcon.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "d:\VoiceToText\new_version\publish\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "d:\VoiceToText\new_version\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
